### ISSUE TITLE
Markup Sketches

### ISSUE THREAD

**Issue by tommymb** [tommymb/saas-website#1]
@muxlowc
Here are my sketches for the SaaS website (I hope it's alright that just used a brush in photoshop rather than markup the sketches since I'm using my original sketches from Interaction Design and we never got them back before school closed).
![Homepage](https://user-images.githubusercontent.com/43139261/78949246-10489a80-7a99-11ea-8460-76166f10d9ec.jpg)
![Signup page](https://user-images.githubusercontent.com/43139261/78949258-12aaf480-7a99-11ea-8969-08a7aa6209d8.jpg)
![Tour page](https://user-images.githubusercontent.com/43139261/78949264-1474b800-7a99-11ea-96e2-4ae2324cd4af.jpg)

**Comment by muxlowc** [comment]
Hey @tommymb  looking good! The only thing I think is missing is a <table> on your tour.html page (how it works page)

I would suggest taking the cards you have on the home page and breaking them down into a table with checkmarks/X's, and maybe put them at the bottom of your How it works page ?
